// Registers every API handler (importing a module is what registers it)
import './system'
import './folders'
import './accounts'
import './settings'
import './games'
import './library'
import './helpers'
import './login'
import 'backend/logger/ipc_handler'
import 'backend/downloadmanager/ipc_handler'
import 'backend/steamgrid/ipc_handler'
