import { frontendListenerSlot, makeHandlerInvoker, makeListenerCaller } from '../ipc'

export const notify = makeListenerCaller('notify')
export const openLoginPage = makeListenerCaller('openLoginPage')
export const quit = makeListenerCaller('quit')
export const showAboutWindow = makeListenerCaller('showAboutWindow')
export const createNewWindow = makeListenerCaller('createNewWindow')
export const readConfig = makeHandlerInvoker('readConfig')
export const isLoggedIn = makeHandlerInvoker('isLoggedIn')
export const writeConfig = makeHandlerInvoker('writeConfig')
export const kill = makeHandlerInvoker('kill')
export const abort = makeListenerCaller('abort')
export const getUserInfo = makeHandlerInvoker('getUserInfo')
export const getAmazonUserInfo = makeHandlerInvoker('getAmazonUserInfo')
export const getGameInfo = makeHandlerInvoker('getGameInfo')
export const getAchievements = makeHandlerInvoker('getAchievements')
export const getExtraInfo = makeHandlerInvoker('getExtraInfo')
export const getPrivateBranchPassword = makeHandlerInvoker('getPrivateBranchPassword')
export const setPrivateBranchPassword = makeHandlerInvoker('setPrivateBranchPassword')
// REDmod integration
export const getAvailableCyberpunkMods = makeHandlerInvoker('getAvailableCyberpunkMods')
export const setCyberpunModConfig = makeHandlerInvoker('setCyberpunkModConfig')
export const getGameSettings = makeHandlerInvoker('getGameSettings')
export const getInstallInfo = makeHandlerInvoker('getInstallInfo')

export const onConnectivityChanged = frontendListenerSlot('connectivity-changed')
export const getConnectivityStatus = makeHandlerInvoker('get-connectivity-status')
export const setConnectivityOnline = makeListenerCaller('set-connectivity-online')
export const connectivityChanged = makeListenerCaller('connectivity-changed')
export const isNative = makeHandlerInvoker('isNative')
export const setTitleBarOverlay = makeListenerCaller('setTitleBarOverlay')
export const isGameAvailable = makeHandlerInvoker('isGameAvailable')
